CMB:
    cmb: True
    seed: 1
    r: 0
    Alens: 1

Foregrounds:

    fit_spectral_index: True

    # Thermal Dust emission
    Dust: True
    model_d: 'd0'
    nu0_d: 150
    temp: 20
    
    # Synchrotron emission
    Synchrotron: False
    model_s: 's0'
    nu0_s: 150
    
    # CO line emission
    CO: False
    nu0_co: 230.538

    nside_fit: 4
    nside_pix: 4
    method: 'L-BFGS-B'
    npix_fit: 5
    fit_all_at_same_time: True

MapMaking:
    qubic:
        npointings: 3000
        nsub: 4
        nside: 64
        iteration: 1
        ndet: 1
        npho150: 1
        npho220: 1
        synthbeam_kmax: 1
        detector_nep: 4.7e-17
        nhwp_angles: 3
        dtheta: 15
        type: 'two'
        convolution: False
        sig_gain: 0.00000001
        fit_gain: True
    sky:
        RA_center: 100
        DEC_center: -157
    planck:
        level_planck_noise: 1
        nintegr: 5
        thr: 0.15
        kappa: 0
        fwhm_kappa: 0
        30GHz: False
        44GHz: False
        70GHz: False
        100GHz: True
        143GHz: True
        217GHz: True
        353GHz: True
    pcg:
        maxiter: 20
        tol: 1.0e-10
        k: 2000
    initial:
        fwhm_x0: 0.00
        set_cmb_to_0: 1
        set_dust_to_0: 1
        set_sync_to_0: 1
        set_co_to_0: 1
        mean_beta_x0: 1.54
        sig_beta_x0: 0.05
        sig_map: 0
        qubic_patch_cmb: 1
        qubic_patch_dust: 1
        qubic_patch_sync: 1
        qubic_patch_co: 1


Plots:
    conv_beta: True
    conv_gain: True
    maps: True
    fake_conv: 0.00
    gif: True
    thr_plot: 0.15

save: 1
foldername: 'd0_nside2_noisy'
filename: 'file'
lastite: True
