CMB:
    cmb: True
    seed: 1
    r: 0
    Alens: 1

Foregrounds:

    fit_spectral_index: True
    type: 'parametric'

    # Thermal Dust emission
    Dust: True
    beta_d_init: 1.54
    model_d: 'd1'
    nu0_d: 150
    temp: 20
    l_corr: 2000000000
    Ad: 1
    
    # Synchrotron emission
    Synchrotron: False
    beta_s_init: -3
    model_s: 's0'
    nu0_s: 150
    As: 1
    
    # CO line emission
    CO: False
    nu0_co: 230.538

    nside_fit: 1
    nside_pix: 1
    method: 'L-BFGS-B'
    npix_fit: 10
    fit_all_at_same_time: False

MapMaking:
    qubic:
        npointings: 100
        nsub: 4
        nside: 64
        iteration: 1
        ndet: 0
        npho150: 0
        npho220: 0
        synthbeam_kmax: 1
        detector_nep: 4.7e-17
        nhwp_angles: 3
        dtheta: 15
        type: 'wide'
        convolution: False
        sig_gain: 0.
        fit_gain: False
    sky:
        RA_center: 0
        DEC_center: -57
    planck:
        level_planck_noise: 0
        nintegr: 2
        thr: 0.2
        kappa: 0
        fwhm_kappa: 0
        30GHz: False
        44GHz: False
        70GHz: False
        100GHz: True
        143GHz: True
        217GHz: True
        353GHz: True
        fixpixels: False
    pcg:
        maxiter: 10
        tol: 1.0e-10
        k: 300
    initial:
        fwhm_x0: 0.00
        set_cmb_to_0: 1
        set_dust_to_0: 1
        set_sync_to_0: 1
        set_co_to_0: 1
        mean_beta_x0: 1.54
        sig_beta_x0: 0.00000000001
        sig_map: 0
        qubic_patch_cmb: 1
        qubic_patch_dust: 1
        qubic_patch_sync: 1
        qubic_patch_co: 1


Plots:
    conv_beta: True
    conv_gain: False
    maps: True
    fake_conv: 0.
    gif: True
    thr_plot: 0.2

save: 1
foldername: 'forecastpaper_dualband'
filename: 'file'
lastite: True
