CMB:
    cmb: True
    seed: 1
    r: 0
    Alens: 1

Foregrounds:
    # Thermal Dust emission
    Dust: True
    model_d: 'd0'
    nu0_d: 150
    temp: 20

    # Synchrotron emission
    Synchrotron: False
    model_s: 's0'
    nu0_s: 23
    
    # CO line emission
    CO: False
    nu0_co: 230.538

    nside_fit: 0
    nside_pix: 0

MapMaking:
    qubic:
        npointings: 400
        nsub: 4
        nside: 64
        iteration: 1
        ndet: 1
        npho150: 1
        npho220: 1
        synthbeam_kmax: 1
        detector_nep: 4.7e-17
        nhwp_angles: 3
        type: 'two'
        convolution: False
        sig_gain: 0.000000001
    sky:
        RA_center: 0
        DEC_center: -57
    planck:
        level_planck_noise: 1
        nintegr: 2
        thr: 0.1
        kappa: 0
        30GHz: False
        44GHz: False
        70GHz: False
        100GHz: True
        143GHz: True
        217GHz: True
        353GHz: True
    pcg:
<<<<<<< HEAD
        maxiter: 20 #300 usual
        tol: 1.0e-30 #1e-5 usual, if we want to get tolerance limited then use tol:1e-5 and k=1000
        k: 1000 #maximum of iterations for the whole PCG+updatespectralindex process, the tolerance of the minimization for the updatespectralindex process is hardcoded (1e-5 or 1e-6 depending if constant or varying case)
=======
        maxiter: 20
        tol: 1.0e-30
        k: 100
>>>>>>> main
    initial:
        fwhm_x0: 0.00
        set_cmb_to_0: 1
        set_dust_to_0: 1
        set_sync_to_0: 1
        set_co_to_0: 1
        mean_beta_x0: 1.54
        sig_beta_x0: 0.0000000001
        sig_map: 0
        qubic_patch_cmb: 1
        qubic_patch_dust: 1
        qubic_patch_sync: 1
        qubic_patch_co: 1


Plots:
    conv_beta: True
    maps: True
    fake_conv: 0.0078
    gif: True

<<<<<<< HEAD
save: 5
foldername: 'test'
filename: 'mytest'
=======
save: 1
foldername: 'CMM_noise'
filename: 'CMM1_1'
>>>>>>> main
