CMB:
    cmb: True
    seed: 1
    r: 0
    Alens: 1

Foregrounds:
    # Thermal Dust emission
    Dust: True
    model_d: 'd1'
    nu0_d: 150
    temp: 20

    # Synchrotron emission
    Synchrotron: False
    model_s: 's0'
    nu0_s: 23

    nside_fit: 2
    nside_pix: 2
    # CO line emission
    CO: False
    nu0_co: 230.538

MapMaking:
    qubic:
        npointings: 100
        nsub: 4
        nside: 64
        iteration: 1
        ndet: 0
        npho150: 0
        npho220: 0
        synthbeam_kmax: 1
        detector_nep: 4.7e-17
        nhwp_angles: 3
        type: 'wide'
        convolution: False
        sig_gain: 0.000000001
    sky:
        RA_center: 100
        DEC_center: -157
    planck:
        level_planck_noise: 0
        nintegr: 2
        thr: 0.1
        kappa: 1
        30GHz: False
        44GHz: False
        70GHz: False
        100GHz: False
        143GHz: False
        217GHz: True
        353GHz: True
    pcg:
        maxiter: 20
        tol: 1.0e-30
        k: 100
    initial:
        fwhm_x0: 0.0
        set_cmb_to_0: 1
        set_dust_to_0: 1
        set_sync_to_0: 1
        set_co_to_0: 1
        mean_beta_x0: 1.54
        sig_beta_x0: 0.0000000000001


Plots:
    conv_beta: False
    maps: True
    fake_conv: 0.0078