CMB:
    cmb: True
    seed: 1
    r: 0
    Alens: 0.5

Foregrounds:

    fit_spectral_index: True
    type: 'parametric'

    # Thermal Dust emission
    Dust_in: True
    Dust_out: True
    beta_d_init: 1.54
    model_d: 'd0'
    nu0_d: 150
    temp: 20
    l_corr: 1000000000000
    Ad: 1
    
    # Synchrotron emission
    Synchrotron_in: True
    Synchrotron_out: True
    beta_s_init: -3
    model_s: 's0'
    nu0_s: 150
    As: 1
    
    # CO line emission
    CO_in: False
    CO_out: False
    nu0_co: 230.538

    nside_fit: 0
    nside_pix: 0
    npix_fit: 48
    fit_all_at_same_time: False

MapMaking:
    qubic:
        npointings: 100                       # Pointing
        nsub: 4                                # Number of sub-acquisitions
        nside: 64                             # Nside of components
        iteration: 1                           
        ndet: 0.3                                # Level of detector noise
        npho150: 0.3                             # Level of photon noise at 150 GHz
        npho220: 0.3                             # Level of photon noise at 220 GHz
        synthbeam_kmax: 1                      # Order of synthetized beam diffraction (k = 1 means 9 peaks)
        detector_nep: 4.7e-17                  # NEP of detector noise
        nhwp_angles: 3                         # Number of angle for HWP
        dtheta: 15                             # Angle for coverage
        type: 'two'                            # Instrumental design (two or wide)
        convolution: False                     # Convolution for accounting angular resolution
        fake_convolution: True                 # Fake convolution to reconstruct convolved components
        sig_gain: 0                            # Standard deviation for detector gains
        fit_gain: False                        # Fitting gain detectors
    sky:
        RA_center: 0          
        DEC_center: -45
    planck:
        level_planck_noise: 1                  # Noise level for Planck data
        nintegr: 2                             # Number of sub-acquisitions for Planck data
        thr: 0.1                               # Threashold to remove planck weight within QUBIC patch
        kappa: 0                               # Weight of Planck data
        fwhm_kappa: 0                          # FWHM for apodized QUBIC patch
        30GHz: False
        44GHz: False
        70GHz: False
        100GHz: True
        143GHz: True
        217GHz: True
        353GHz: True
        fixpixels: False                       # Fixing pixels outside QUBIC patch
        fixI: False
    pcg:
        maxiter: 50
        tol: 1.0e-10
        k: 300
        ites_to_converge: 20 # should be less than k
        noise_rms_variation_tolerance: 1.0e-3
    initial:
        fwhm_x0: 0.00415369 #0.0041
        set_cmb_to_0: 1
        set_dust_to_0: 1
        set_sync_to_0: 1
        set_co_to_0: 1
        mean_beta_x0: 1.54
        sig_beta_x0: 0.0000000000000000000001
        sig_map: 0.
        qubic_patch_cmb: 1
        qubic_patch_dust: 1
        qubic_patch_sync: 1
        qubic_patch_co: 1


Plots:
    conv_beta: True
    conv_gain: False
    conv_rms: True
    maps: True
    fake_conv: 0.
    gif: True
    thr_plot: 0.2

save: 1
foldername: 'forecast_inCMBDustSync_outCMBDustSync_advanced'
filename: 'file'
lastite: True