CMB:
    cmb: True
    seed: 1
    r: 0
    Alens: 1

Foregrounds:

    fit_spectral_index: False

    # Thermal Dust emission
    Dust: True
    model_d: 'd0'
    nu0_d: 150
    temp: 20
    
    # Synchrotron emission
    Synchrotron: False
    model_s: 's0'
    nu0_s: 70
    
    # CO line emission
    CO: False
    nu0_co: 230.538

    nside_fit: 0
    nside_pix: 0

MapMaking:
    qubic:
        npointings: 100
        nsub: 4
        nside: 64
        iteration: 1
        ndet: 0
        npho150: 0
        npho220: 0
        synthbeam_kmax: 1
        detector_nep: 4.7e-17
        nhwp_angles: 3
        dtheta: 15
        type: 'wide'
        convolution: False
        sig_gain: 0.1
        fit_gain: True
    sky:
        RA_center: 0
        DEC_center: -57
    planck:
        level_planck_noise: 0
        nintegr: 2
        thr: 0.2
        thr_plot: 0.1
        kappa: 0
        fwhm_kappa: 0
        30GHz: False
        44GHz: False
        70GHz: True
        100GHz: True
        143GHz: True
        217GHz: True
        353GHz: True
    pcg:
        maxiter: 20 
        tol: 1.0e-30 
        k: 1000 

    initial:
        fwhm_x0: 0.00
        set_cmb_to_0: 1
        set_dust_to_0: 1
        set_sync_to_0: 1
        set_co_to_0: 1
        mean_beta_x0: 1.54
        sig_beta_x0: 0.0000000001
        sig_map: 0
        qubic_patch_cmb: 1
        qubic_patch_dust: 1
        qubic_patch_sync: 1
        qubic_patch_co: 1


Plots:
    conv_beta: True
    conv_gain: True
    maps: True
    fake_conv: 0.0078
    thr_plot: 0.1
    gif: True

save: 5
foldername: 'test'
filename: 'mytest'
